version: '3.9'

services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 512mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: simple_crud
    networks:
      - db_network

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 2222:8080
    networks:
      - db_network

  pg:
    image: dpage/pgadmin4:8.9
    environment:
      PGADMIN_DEFAULT_EMAIL: mvc@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: test123
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 8888:80
    shm_size: 512mb
    #volumes:
    #  - ./pgadmin:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - db_network


networks:
  db_network:
    driver: bridge
