version: '3.9'

services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - ./scipts:/var/scripts
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "test123"
      POSTGRES_DB: "simple_crud"

  adminer:
    image: adminer
    restart: always
    ports:
      - 80:8080
